/**
 * TogoTransit Design System Colors
 */

export interface ThemeColors {
  text: string;
  background: string;
  tint: string;
  tabIconDefault: string;
  tabIconSelected: string;
  primary: string;
  primaryHover: string;
  onPrimary: string;
  primaryContainer: string;
  onPrimaryContainer: string;
  secondary: string;
  onSecondary: string;
  secondaryContainer: string;
  onSecondaryContainer: string;
  tertiary: string;
  onTertiary: string;
  tertiaryContainer: string;
  onTertiaryContainer: string;
  surface: string;
  surfaceDim: string;
  surfaceBright: string;
  surfaceVariant: string;
  onSurface: string;
  onSurfaceVariant: string;
  surfaceContainerLowest: string;
  surfaceContainerLow: string;
  surfaceContainer: string;
  surfaceContainerHigh: string;
  surfaceContainerHighest: string;
  inverseSurface: string;
  inverseOnSurface: string;
  inversePrimary: string;
  outline: string;
  outlineVariant: string;
  surfaceTint: string;
  error: string;
  onError: string;
  errorContainer: string;
  onErrorContainer: string;
  success: string;
  onSuccess: string;
  warning: string;
  primaryFixed: string;
  primaryFixedDim: string;
  onPrimaryFixed: string;
  onPrimaryFixedVariant: string;
  secondaryFixed: string;
  secondaryFixedDim: string;
  onSecondaryFixed: string;
  onSecondaryFixedVariant: string;
  tertiaryFixed: string;
  tertiaryFixedDim: string;
  onTertiaryFixed: string;
  onTertiaryFixedVariant: string;
  textSecondary: string;
  border: string;
}

export const Colors: {
  light: ThemeColors;
  dark: ThemeColors;
} = {
  light: {
    text: '#0b1c30',
    background: '#f8f9ff',
    tint: '#002653',
    tabIconDefault: '#747780',
    tabIconSelected: '#002653',
    primary: '#3b82f6',
    primaryHover: '#2563eb',
    onPrimary: '#ffffff',
    primaryContainer: '#dbeafe',
    onPrimaryContainer: '#1e3a8a',
    secondary: '#059669',
    onSecondary: '#ffffff',
    secondaryContainer: '#d1fae5',
    onSecondaryContainer: '#064e3b',
    tertiary: '#3e1f00',
    onTertiary: '#ffffff',
    tertiaryContainer: '#5e3100',
    onTertiaryContainer: '#db9960',
    surface: '#f3f4f6',
    surfaceDim: '#cbdbf5',
    surfaceBright: '#f8f9ff',
    surfaceVariant: '#e5e7eb',
    onSurface: '#0b1c30',
    onSurfaceVariant: '#747780',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f9fafb',
    surfaceContainer: '#e5e7eb',
    surfaceContainerHigh: '#e5e7eb',
    surfaceContainerHighest: '#11182710',
    inverseSurface: '#213145',
    inverseOnSurface: '#eaf1ff',
    inversePrimary: '#abc7ff',
    outline: '#747780',
    outlineVariant: '#e5e7eb',
    surfaceTint: '#405e92',
    error: '#ef4444',
    onError: '#ffffff',
    errorContainer: '#fef2f2',
    onErrorContainer: '#7f1d1d',
    success: '#10b981',
    onSuccess: '#ffffff',
    warning: '#f59e0b',
    primaryFixed: '#d7e3ff',
    primaryFixedDim: '#abc7ff',
    onPrimaryFixed: '#001b3f',
    onPrimaryFixedVariant: '#264679',
    secondaryFixed: '#ffdbca',
    secondaryFixedDim: '#ffb690',
    onSecondaryFixed: '#341100',
    onSecondaryFixedVariant: '#783200',
    tertiaryFixed: '#ffdcc2',
    tertiaryFixedDim: '#feb87c',
    onTertiaryFixed: '#2e1500',
    onTertiaryFixedVariant: '#6b3b09',
    textSecondary: '#747780',
    border: '#e5e7eb',
  },
  dark: {
    text: '#eaf1ff',
    background: '#0b1c30',
    tint: '#abc7ff',
    tabIconDefault: '#c4c6d0',
    tabIconSelected: '#abc7ff',
    primary: '#60a5fa',
    primaryHover: '#3b82f6',
    onPrimary: '#0b1c30',
    primaryContainer: '#1e3a8a',
    onPrimaryContainer: '#dbeafe',
    secondary: '#34d399',
    onSecondary: '#0b1c30',
    secondaryContainer: '#064e3b',
    onSecondaryContainer: '#d1fae5',
    tertiary: '#ffdcc2',
    onTertiary: '#2e1500',
    tertiaryContainer: '#6b3b09',
    onTertiaryContainer: '#ffdcc2',
    surface: '#1f2937',
    surfaceDim: '#0b1c30',
    surfaceBright: '#3b4759',
    surfaceVariant: '#374151',
    onSurface: '#eaf1ff',
    onSurfaceVariant: '#9ca3af',
    surfaceContainerLowest: '#061323',
    surfaceContainerLow: '#374151',
    surfaceContainer: '#374151',
    surfaceContainerHigh: '#4b5563',
    surfaceContainerHighest: '#ffffff10',
    inverseSurface: '#eaf1ff',
    inverseOnSurface: '#0b1c30',
    inversePrimary: '#002653',
    outline: '#9ca3af',
    outlineVariant: '#4b5563',
    surfaceTint: '#abc7ff',
    error: '#f87171',
    onError: '#690005',
    errorContainer: '#7f1d1d',
    onErrorContainer: '#fef2f2',
    success: '#34d399',
    onSuccess: '#003732',
    warning: '#fbbf24',
    primaryFixed: '#d7e3ff',
    primaryFixedDim: '#abc7ff',
    onPrimaryFixed: '#001b3f',
    onPrimaryFixedVariant: '#264679',
    secondaryFixed: '#ffdbca',
    secondaryFixedDim: '#ffb690',
    onSecondaryFixed: '#341100',
    onSecondaryFixedVariant: '#783200',
    tertiaryFixed: '#ffdcc2',
    tertiaryFixedDim: '#feb87c',
    onTertiaryFixed: '#2e1500',
    onTertiaryFixedVariant: '#6b3b09',
    textSecondary: '#9ca3af',
    border: '#374151',
  },
};
