/**
 * TogoTransit Design System Colors
 */

export interface ThemeColors {
  text: string;
  background: string;
  tint: string;
  tabIconDefault: string;
  tabIconSelected: string;
  primary: string;
  primaryHover: string;
  onPrimary: string;
  primaryContainer: string;
  onPrimaryContainer: string;
  secondary: string;
  onSecondary: string;
  secondaryContainer: string;
  onSecondaryContainer: string;
  tertiary: string;
  onTertiary: string;
  tertiaryContainer: string;
  onTertiaryContainer: string;
  surface: string;
  surfaceDim: string;
  surfaceBright: string;
  surfaceVariant: string;
  onSurface: string;
  onSurfaceVariant: string;
  surfaceContainerLowest: string;
  surfaceContainerLow: string;
  surfaceContainer: string;
  surfaceContainerHigh: string;
  surfaceContainerHighest: string;
  inverseSurface: string;
  inverseOnSurface: string;
  inversePrimary: string;
  outline: string;
  outlineVariant: string;
  surfaceTint: string;
  error: string;
  onError: string;
  errorContainer: string;
  onErrorContainer: string;
  success: string;
  onSuccess: string;
  warning: string;
  primaryFixed: string;
  primaryFixedDim: string;
  onPrimaryFixed: string;
  onPrimaryFixedVariant: string;
  secondaryFixed: string;
  secondaryFixedDim: string;
  onSecondaryFixed: string;
  onSecondaryFixedVariant: string;
  tertiaryFixed: string;
  tertiaryFixedDim: string;
  onTertiaryFixed: string;
  onTertiaryFixedVariant: string;
  textSecondary: string;
  border: string;
}

export const Colors: {
  light: ThemeColors;
  dark: ThemeColors;
} = {
  light: {
    text: '#0b1c30',
    background: '#f8f9ff',
    tint: '#9d4300',
    tabIconDefault: '#5f6269',
    tabIconSelected: '#9d4300',
    primary: '#9d4300',
    primaryHover: '#7a3400',
    onPrimary: '#ffffff',
    primaryContainer: '#ffe4cc',
    onPrimaryContainer: '#5c2400',
    secondary: '#059669',
    onSecondary: '#ffffff',
    secondaryContainer: '#d1fae5',
    onSecondaryContainer: '#064e3b',
    tertiary: '#3e1f00',
    onTertiary: '#ffffff',
    tertiaryContainer: '#5e3100',
    onTertiaryContainer: '#db9960',
    surface: '#f3f4f6',
    surfaceDim: '#cbdbf5',
    surfaceBright: '#f8f9ff',
    surfaceVariant: '#e5e7eb',
    onSurface: '#0b1c30',
    onSurfaceVariant: '#5f6269',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f9fafb',
    surfaceContainer: '#e5e7eb',
    surfaceContainerHigh: '#e5e7eb',
    surfaceContainerHighest: '#11182710',
    inverseSurface: '#213145',
    inverseOnSurface: '#eaf1ff',
    inversePrimary: '#abc7ff',
    outline: '#5f6269',
    outlineVariant: '#e5e7eb',
    surfaceTint: '#405e92',
    error: '#ef4444',
    onError: '#ffffff',
    errorContainer: '#fef2f2',
    onErrorContainer: '#7f1d1d',
    success: '#10b981',
    onSuccess: '#003732',
    warning: '#f59e0b',
    primaryFixed: '#d7e3ff',
    primaryFixedDim: '#abc7ff',
    onPrimaryFixed: '#001b3f',
    onPrimaryFixedVariant: '#264679',
    secondaryFixed: '#ffdbca',
    secondaryFixedDim: '#ffb690',
    onSecondaryFixed: '#341100',
    onSecondaryFixedVariant: '#783200',
    tertiaryFixed: '#ffdcc2',
    tertiaryFixedDim: '#feb87c',
    onTertiaryFixed: '#2e1500',
    onTertiaryFixedVariant: '#6b3b09',
    textSecondary: '#5f6269',
    border: '#e5e7eb',
  },
  dark: {
    text: '#f5f7ff',
    background: '#070d1a',
    tint: '#fd761a',
    tabIconDefault: '#838ea8',
    tabIconSelected: '#fd761a',
    primary: '#fd761a',
    primaryHover: '#e8650a',
    onPrimary: '#1a0800',
    primaryContainer: '#3a2414',
    onPrimaryContainer: '#ffb673',
    secondary: '#34d399',
    onSecondary: '#0b1c30',
    secondaryContainer: '#064e3b',
    onSecondaryContainer: '#d1fae5',
    tertiary: '#ffdcc2',
    onTertiary: '#2e1500',
    tertiaryContainer: '#6b3b09',
    onTertiaryContainer: '#ffdcc2',
    surface: '#131b2c',
    surfaceDim: '#04070d',
    surfaceBright: '#26314a',
    surfaceVariant: '#1b2436',
    onSurface: '#f5f7ff',
    onSurfaceVariant: '#a3acc2',
    surfaceContainerLowest: '#0d1420',
    surfaceContainerLow: '#111a2b',
    surfaceContainer: '#161f33',
    surfaceContainerHigh: '#1d283e',
    surfaceContainerHighest: '#26314a',
    inverseSurface: '#f5f7ff',
    inverseOnSurface: '#070d1a',
    inversePrimary: '#9d4300',
    outline: '#838ea8',
    outlineVariant: '#2a3450',
    surfaceTint: '#fd761a',
    error: '#f87171',
    onError: '#690005',
    errorContainer: '#7f1d1d',
    onErrorContainer: '#fef2f2',
    success: '#34d399',
    onSuccess: '#003732',
    warning: '#fbbf24',
    primaryFixed: '#d7e3ff',
    primaryFixedDim: '#abc7ff',
    onPrimaryFixed: '#001b3f',
    onPrimaryFixedVariant: '#264679',
    secondaryFixed: '#ffdbca',
    secondaryFixedDim: '#ffb690',
    onSecondaryFixed: '#341100',
    onSecondaryFixedVariant: '#783200',
    tertiaryFixed: '#ffdcc2',
    tertiaryFixedDim: '#feb87c',
    onTertiaryFixed: '#2e1500',
    onTertiaryFixedVariant: '#6b3b09',
    textSecondary: '#a3acc2',
    border: '#1e2740',
  },
};
